"! <p class="shorttext synchronized" lang="en"></p>
"!
CLASS zcx_io_stream_error DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_IO_STREAM_ERROR IMPLEMENTATION.
ENDCLASS.
